server:
  port: 8080

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yenpu-upyoung/myupconfig-service.git
          username: ${GIT_USER}
          password: ${GIT_PWD}
          default-label: master
    gcp:
      logging:
        enabled: true

encrypt:
  key: ${ENCRYPT_KEY}